/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Resource = {
  _type: "resource";
  type?: "pdf" | "link" | "repo" | "code" | "slides";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?:
    | "Code"
    | "Database"
    | "Cpu"
    | "Layers"
    | "Shield"
    | "Zap"
    | "Server"
    | "Layout"
    | "Globe"
    | "Terminal"
    | "CheckCircle"
    | "BookOpen";
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: BlockContent;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: BlockContent;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/lib/queries.ts
// Variable: COURSES_LIST_QUERY
// Query: *[_type == "course"] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    level,    price,    popular,    studentCount,    coverImage,    instructor->{      _id,      name,      "slug": slug.current,      photo    },    category->{      _id,      title,      "slug": slug.current    },    "moduleCount": count(modules),    "totalDuration": math::sum(modules[].lessons[]->duration)  }
export type COURSES_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  moduleCount: number | null;
  totalDuration: number | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)] {    "slug": slug.current  }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    coverImage,    level,    price,    popular,    studentCount,    learningOutcomes[]{      _key,      icon,      title,      description    },    instructor->{      _id,      name,      "slug": slug.current,      photo,      expertise,      bio    },    category->{      _id,      title,      "slug": slug.current    },    "totalDuration": math::sum(modules[].lessons[]->duration),    modules[]{      _key,      title,      summary,      lessons[]->{        _id,        title,        "slug": slug.current,        duration,        freePreview      }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon:
      | "BookOpen"
      | "CheckCircle"
      | "Code"
      | "Cpu"
      | "Database"
      | "Globe"
      | "Layers"
      | "Layout"
      | "Server"
      | "Shield"
      | "Terminal"
      | "Zap"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
  instructor: {
    _id: string;
    name: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    expertise: Array<string> | null;
    bio: BlockContent | null;
  } | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  totalDuration: number | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      duration: number | null;
      freePreview: boolean | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)] {    "slug": slug.current  }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    thumbnail,    duration,    freePreview,    studentCount,    notes,    keyPoints,    proTip,    resources[]{      _key,      type,      title,      description,      url    },    "course": *[_type == "course" && references(^._id)][0] {      _id,      title,      "slug": slug.current,      instructor->{        _id,        name,        "slug": slug.current,        photo      },      modules[]{        _key,        title,        lessons[]->{          _id,          title,          "slug": slug.current,          duration,          freePreview        }      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  videoUrl: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  duration: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  notes: BlockContent | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "code" | "link" | "pdf" | "repo" | "slides" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    instructor: {
      _id: string;
      name: string | null;
      slug: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      lessons: Array<{
        _id: string;
        title: string | null;
        slug: string | null;
        duration: number | null;
        freePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTORS_LIST_QUERY
// Query: *[_type == "instructor"] | order(name asc) {    _id,    name,    "slug": slug.current,    photo,    expertise  }
export type INSTRUCTORS_LIST_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  expertise: Array<string> | null;
}>;

// Source: ../sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    photo,    expertise,    bio,    "courses": *[_type == "course" && references(^._id)] {      _id,      title,      "slug": slug.current,      summary,      level,      price,      popular,      studentCount,      coverImage,      category->{        _id,        title,        "slug": slug.current      },      "moduleCount": count(modules),      "totalDuration": math::sum(modules[].lessons[]->duration)    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  expertise: Array<string> | null;
  bio: BlockContent | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    category: {
      _id: string;
      title: string | null;
      slug: string | null;
    } | null;
    moduleCount: number | null;
    totalDuration: number | null;
  }>;
} | null;

// Source: ../sanity/lib/queries.ts
// Variable: CATEGORIES_LIST_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type CATEGORIES_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  courseCount: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    level,\n    price,\n    popular,\n    studentCount,\n    coverImage,\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    "moduleCount": count(modules),\n    "totalDuration": math::sum(modules[].lessons[]->duration)\n  }\n': COURSES_LIST_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage,\n    level,\n    price,\n    popular,\n    studentCount,\n    learningOutcomes[]{\n      _key,\n      icon,\n      title,\n      description\n    },\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo,\n      expertise,\n      bio\n    },\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    "totalDuration": math::sum(modules[].lessons[]->duration),\n    modules[]{\n      _key,\n      title,\n      summary,\n      lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        duration,\n        freePreview\n      }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    thumbnail,\n    duration,\n    freePreview,\n    studentCount,\n    notes,\n    keyPoints,\n    proTip,\n    resources[]{\n      _key,\n      type,\n      title,\n      description,\n      url\n    },\n    "course": *[_type == "course" && references(^._id)][0] {\n      _id,\n      title,\n      "slug": slug.current,\n      instructor->{\n        _id,\n        name,\n        "slug": slug.current,\n        photo\n      },\n      modules[]{\n        _key,\n        title,\n        lessons[]->{\n          _id,\n          title,\n          "slug": slug.current,\n          duration,\n          freePreview\n        }\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    photo,\n    expertise\n  }\n': INSTRUCTORS_LIST_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    photo,\n    expertise,\n    bio,\n    "courses": *[_type == "course" && references(^._id)] {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      level,\n      price,\n      popular,\n      studentCount,\n      coverImage,\n      category->{\n        _id,\n        title,\n        "slug": slug.current\n      },\n      "moduleCount": count(modules),\n      "totalDuration": math::sum(modules[].lessons[]->duration)\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "courseCount": count(*[_type == "course" && references(^._id)])\n  }\n': CATEGORIES_LIST_QUERY_RESULT;
  }
}
